//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyglotDesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupaUczen
    {
        public int GrupaId { get; set; }
        public int UczenId { get; set; }
        public Nullable<System.DateTime> DataDolaczenia { get; set; }
        public Nullable<System.DateTime> DataZakonczenia { get; set; }
        public string Status { get; set; }
    
        public virtual Grupa Grupa { get; set; }
        public virtual Uczen Uczen { get; set; }
    }
}
