//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyglotDesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupa
    {
        public Grupa()
        {
            this.GrupaUczen = new HashSet<GrupaUczen>();
            this.Zajecia = new HashSet<Zajecia>();
            this.Zajecia1 = new HashSet<Zajecia>();
        }
    
        public int GrupaId { get; set; }
        public int KursId { get; set; }
        public int LektorId { get; set; }
        public Nullable<int> SalaId { get; set; }
        public Nullable<int> PodrecznikId { get; set; }
        public string Nazwa { get; set; }
        public string DzienTygodnia { get; set; }
        public Nullable<System.TimeSpan> GodzinaStart { get; set; }
        public Nullable<System.TimeSpan> GodzinaKoniec { get; set; }
        public string Tryb { get; set; }
        public string Status { get; set; }
    
        public virtual Kurs Kurs { get; set; }
        public virtual Lektor Lektor { get; set; }
        public virtual Podrecznik Podrecznik { get; set; }
        public virtual Sala Sala { get; set; }
        public virtual ICollection<GrupaUczen> GrupaUczen { get; set; }
        public virtual ICollection<Zajecia> Zajecia { get; set; }
        public virtual ICollection<Zajecia> Zajecia1 { get; set; }
    }
}
