//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyglotDesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jezyk
    {
        public Jezyk()
        {
            this.Kurs = new HashSet<Kurs>();
            this.LektorJezyk = new HashSet<LektorJezyk>();
            this.Podrecznik = new HashSet<Podrecznik>();
            this.UczenKurs = new HashSet<UczenKurs>();
        }
    
        public int JezykId { get; set; }
        public string Kod { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
    
        public virtual ICollection<Kurs> Kurs { get; set; }
        public virtual ICollection<LektorJezyk> LektorJezyk { get; set; }
        public virtual ICollection<Podrecznik> Podrecznik { get; set; }
        public virtual ICollection<UczenKurs> UczenKurs { get; set; }
    }
}
