//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyglotDesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurs
    {
        public Kurs()
        {
            this.Grupa = new HashSet<Grupa>();
            this.Platnosc = new HashSet<Platnosc>();
            this.UczenKurs = new HashSet<UczenKurs>();
        }
    
        public int KursId { get; set; }
        public int JezykId { get; set; }
        public int RodzajKursuId { get; set; }
        public string NazwaKursu { get; set; }
        public string Poziom { get; set; }
        public Nullable<decimal> CenaMiesieczna { get; set; }
        public string Tryb { get; set; }
    
        public virtual ICollection<Grupa> Grupa { get; set; }
        public virtual Jezyk Jezyk { get; set; }
        public virtual RodzajKursu RodzajKursu { get; set; }
        public virtual ICollection<Platnosc> Platnosc { get; set; }
        public virtual ICollection<UczenKurs> UczenKurs { get; set; }
    }
}
