//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyglotDesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LektorJezyk
    {
        public int LektorJezykId { get; set; }
        public int LektorId { get; set; }
        public int JezykId { get; set; }
        public string PoziomKompetencji { get; set; }
        public Nullable<int> DoswiadczenieLat { get; set; }
        public string Certyfikat { get; set; }
        public string Specjalizacja { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Jezyk Jezyk { get; set; }
        public virtual Lektor Lektor { get; set; }
    }
}
