//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyglotDesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lektor
    {
        public Lektor()
        {
            this.Grupa = new HashSet<Grupa>();
            this.LektorJezyk = new HashSet<LektorJezyk>();
            this.Wynagrodzenie = new HashSet<Wynagrodzenie>();
            this.Zajecia = new HashSet<Zajecia>();
            this.UczenKurs = new HashSet<UczenKurs>();
        }
    
        public int LektorId { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public decimal StawkaGodzinowa { get; set; }
        public string FormaZatrudnienia { get; set; }
        public Nullable<System.DateTime> DataZatrudnienia { get; set; }
        public Nullable<bool> Aktywny { get; set; }
    
        public virtual ICollection<Grupa> Grupa { get; set; }
        public virtual ICollection<LektorJezyk> LektorJezyk { get; set; }
        public virtual ICollection<Wynagrodzenie> Wynagrodzenie { get; set; }
        public virtual ICollection<Zajecia> Zajecia { get; set; }
        public virtual ICollection<UczenKurs> UczenKurs { get; set; }
    }
}
