//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyglotDesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obecnosc
    {
        public int ObecnoscId { get; set; }
        public int ZajeciaId { get; set; }
        public int UczenId { get; set; }
        public string Status { get; set; }
        public string Uwagi { get; set; }
        public string RecordStatus { get; set; }
    
        public virtual Uczen Uczen { get; set; }
        public virtual Zajecia Zajecia { get; set; }
    }
}
