//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyglotDesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocena
    {
        public int OcenaId { get; set; }
        public int ZajeciaId { get; set; }
        public int UczenId { get; set; }
        public string Rodzaj { get; set; }
        public string Wartosc { get; set; }
        public Nullable<System.DateTime> DataOceny { get; set; }
        public string TematOceny { get; set; }
        public string Status { get; set; }
    
        public virtual Uczen Uczen { get; set; }
        public virtual Zajecia Zajecia { get; set; }
    }
}
