//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyglotDesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platnosc
    {
        public int PlatnoscId { get; set; }
        public int UczenId { get; set; }
        public int KursId { get; set; }
        public string Okres { get; set; }
        public Nullable<decimal> Kwota { get; set; }
        public Nullable<System.DateTime> DataPlatnosci { get; set; }
        public string Metoda { get; set; }
        public string Status { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Kurs Kurs { get; set; }
        public virtual Uczen Uczen { get; set; }
    }
}
