//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyglotDesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podrecznik
    {
        public Podrecznik()
        {
            this.Grupa = new HashSet<Grupa>();
            this.UczenKurs = new HashSet<UczenKurs>();
        }
    
        public int PodrecznikId { get; set; }
        public int JezykId { get; set; }
        public string Tytul { get; set; }
        public string Autor { get; set; }
        public string Wydawnictwo { get; set; }
        public string Poziom { get; set; }
        public Nullable<int> RokWydania { get; set; }
        public string Opis { get; set; }
    
        public virtual ICollection<Grupa> Grupa { get; set; }
        public virtual Jezyk Jezyk { get; set; }
        public virtual ICollection<UczenKurs> UczenKurs { get; set; }
    }
}
