//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyglotDesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RodzajKursu
    {
        public RodzajKursu()
        {
            this.Kurs = new HashSet<Kurs>();
            this.UczenKurs = new HashSet<UczenKurs>();
        }
    
        public int RodzajKursuId { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
    
        public virtual ICollection<Kurs> Kurs { get; set; }
        public virtual ICollection<UczenKurs> UczenKurs { get; set; }
    }
}
