//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyglotDesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        public Sala()
        {
            this.Grupa = new HashSet<Grupa>();
            this.Zajecia = new HashSet<Zajecia>();
        }
    
        public int SalaId { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> Pojemnosc { get; set; }
        public string Lokalizacja { get; set; }
        public string Wyposazenie { get; set; }
        public string Typ { get; set; }
    
        public virtual ICollection<Grupa> Grupa { get; set; }
        public virtual ICollection<Zajecia> Zajecia { get; set; }
    }
}
