//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyglotDesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UczenKurs
    {
        public int UczenKursId { get; set; }
        public int UczenId { get; set; }
        public int KursId { get; set; }
        public int JezykId { get; set; }
        public int RodzajKursuId { get; set; }
        public int LektorId { get; set; }
        public int PodrecznikId { get; set; }
        public string Status { get; set; }
    
        public virtual Jezyk Jezyk { get; set; }
        public virtual Kurs Kurs { get; set; }
        public virtual Lektor Lektor { get; set; }
        public virtual Podrecznik Podrecznik { get; set; }
        public virtual RodzajKursu RodzajKursu { get; set; }
        public virtual Uczen Uczen { get; set; }
    }
}
