//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyglotDesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uczen
    {
        public Uczen()
        {
            this.GrupaUczen = new HashSet<GrupaUczen>();
            this.Obecnosc = new HashSet<Obecnosc>();
            this.Ocena = new HashSet<Ocena>();
            this.Platnosc = new HashSet<Platnosc>();
            this.Zajecia = new HashSet<Zajecia>();
            this.UczenKurs = new HashSet<UczenKurs>();
        }
    
        public int UczenId { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string PESEL { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public Nullable<System.DateTime> DataZapisu { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<GrupaUczen> GrupaUczen { get; set; }
        public virtual ICollection<Obecnosc> Obecnosc { get; set; }
        public virtual ICollection<Ocena> Ocena { get; set; }
        public virtual ICollection<Platnosc> Platnosc { get; set; }
        public virtual ICollection<Zajecia> Zajecia { get; set; }
        public virtual ICollection<UczenKurs> UczenKurs { get; set; }
    }
}
