//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyglotDesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wynagrodzenie
    {
        public int WynagrodzenieId { get; set; }
        public int LektorId { get; set; }
        public string Okres { get; set; }
        public Nullable<decimal> LiczbaGodzin { get; set; }
        public Nullable<decimal> StawkaGodzinowa { get; set; }
        public Nullable<decimal> KwotaDoWyplaty { get; set; }
        public Nullable<System.DateTime> DataWyplaty { get; set; }
        public string Status { get; set; }
    
        public virtual Lektor Lektor { get; set; }
    }
}
