//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyglotDesktopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zajecia
    {
        public Zajecia()
        {
            this.Obecnosc = new HashSet<Obecnosc>();
            this.Ocena = new HashSet<Ocena>();
        }
    
        public int ZajeciaId { get; set; }
        public Nullable<int> GrupaId { get; set; }
        public Nullable<int> LektorId { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.TimeSpan> GodzinaStart { get; set; }
        public Nullable<System.TimeSpan> GodzinaKoniec { get; set; }
        public string Temat { get; set; }
        public string Uwagi { get; set; }
        public Nullable<int> UczenId { get; set; }
        public string Tryb { get; set; }
        public string DzienTygodnia { get; set; }
        public string Status { get; set; }
        public Nullable<int> SalaId { get; set; }
        public string RodzajZajec { get; set; }
    
        public virtual Grupa Grupa { get; set; }
        public virtual Grupa Grupa1 { get; set; }
        public virtual Lektor Lektor { get; set; }
        public virtual ICollection<Obecnosc> Obecnosc { get; set; }
        public virtual ICollection<Ocena> Ocena { get; set; }
        public virtual Sala Sala { get; set; }
        public virtual Uczen Uczen { get; set; }
    }
}
